# Generated by Django 3.1.3 on 2020-12-12 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'company',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'project',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectManagement.company')),
            ],
            options={
                'db_table': 'user',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('due_date', models.DateField()),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectManagement.project')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='projectManagement.user')),
            ],
            options={
                'db_table': 'task',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('task', models.ManyToManyField(to='projectManagement.Task')),
            ],
            options={
                'db_table': 'tag',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='user',
            field=models.ManyToManyField(to='projectManagement.User'),
        ),
        migrations.CreateModel(
            name='BillingInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=20)),
                ('zipCode', models.IntegerField(default=0)),
                ('country', models.CharField(max_length=20)),
                ('ccc', models.IntegerField(default=0)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='projectManagement.company')),
            ],
            options={
                'db_table': 'billing_info',
                'ordering': ['cif'],
            },
        ),
    ]
